# Generated by Django 4.0.5 on 2022-06-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=45)),
                ('email', models.CharField(max_length=45, unique=True)),
                ('Password', models.CharField(default='', max_length=45, null=True)),
                ('line', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
